name: Build and Deploy to Staging

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

            # Build and push the API + Frontend images
      - name: Build & push Docker images
        run: |
              # Log in to GHCR
              echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    
              # API image 
              docker build \
                -t ghcr.io/annanorlyk/devops-calculator-api:staging \
                -f API/Dockerfile \
                .
    
              docker push ghcr.io/annanorlyk/devops-calculator-api:staging
    
              # Frontend image 
              docker build \
                -t ghcr.io/annanorlyk/devops-calculator-frontend:staging \
                -f frontend/Dockerfile \
                frontend
    
              docker push ghcr.io/annanorlyk/devops-calculator-frontend:staging

      # Deliver docker-compose.yml to staging
      - name: Deliver Docker Compose file to staging
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "dowa/"


      - name: Deliver migrations to staging
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "db/migrations/*"
          target: "dowa/db/migrations/"


      - name: Create .env on staging
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd dowa
            cat <<EOF > .env
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            EOF

      # Run Docker Compose on staging
      - name: Run Docker Compose on staging server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd dowa
            docker compose pull
            docker compose up -d
