name: Unit Tests & Mutation Tests

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Install tools
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker

      - name: Configure .env
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: Start Docker Compose
        run: docker compose -f docker-compose.yml up -d
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

      - name: Wait for DB
      # Wait a few seconds for MariaDB to initialize
        run: sleep 10  

      - name: Run Unit Tests
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Generate Coverage Report
        run: |
          reportgenerator \
            -reports:"TestResults/**/coverage.cobertura.xml" \
            -targetdir:coverage-report \
            -reporttypes:Html

      - name: Run Mutation Tests
        run: dotnet stryker --break-at 80

      - name: Upload Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Coverage
          path: coverage-report

      - name: Upload Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: StrykerReport
          path: StrykerOutput

